import * as FileSystem from 'expo-file-system';
import workouts from '../../workouts.json';
const dir = FileSystem.documentDirectory;
const starterJSON = {
    "workouts": [
        {"name": "Single-Leg Press", "target": "Quadriceps", "rating": 9.6, "data": []},
        {"name": "Palms-down wrist curl over bench", "target": "Forearms", "rating": 9.5, "data": []},
        {"name": "Dumbbell front raise to lateral raise", "target": "Shoulders", "rating": 9.5, "data": []},
        {"name": "Incline Hammer Curls", "target": "Biceps", "rating": 9.5, "data": []},
        {"name": "Clean and press", "target": "Shoulders", "rating": 9.4, "data": []},
        {"name": "Palms-up wrist curl over bench", "target": "Forearms", "rating": 9.4, "data": []},
        {"name": "Barbell Full Squat", "target": "Quadriceps", "rating": 9.4, "data": []},
        {"name": "Barbell Deadlift", "target": "Hamstrings", "rating": 9.4, "data": []},
        {"name": "Single-arm palm-in dumbbell shoulder press", "target": "Shoulders", "rating": 9.4, "data": []},
        {"name": "Romanian Deadlift With Dumbbells", "target": "Hamstrings", "rating": 9.4, "data": []},
        {"name": "Single-arm kettlebell push-press", "target": "Shoulders", "rating": 9.3, "data": []},
        {"name": "Military press", "target": "Shoulders", "rating": 9.3, "data": []},
        {"name": "Dumbbell V-Sit Cross Jab", "target": "Abdominals", "rating": 9.3, "data": []},
        {"name": "Standing palms-in shoulder press", "target": "Shoulders", "rating": 9.3, "data": []},
        {"name": "Standing cable low-to-high twist", "target": "Abdominals", "rating": 9.3, "data": []},
        {"name": "Decline EZ-bar skullcrusher", "target": "Triceps", "rating": 9.3, "data": []},
        {"name": "Standing behind-the-back wrist curl", "target": "Forearms", "rating": 9.3, "data": []},
        {"name": "Seated finger curl", "target": "Forearms", "rating": 9.3, "data": []},
        {"name": "Wide-grip barbell curl", "target": "Biceps", "rating": 9.3, "data": []},
        {"name": "Dumbbell spell caster", "target": "Abdominals", "rating": 9.3, "data": []},
        {"name": "Dumbbell Bench Press", "target": "Chest", "rating": 9.2, "data": []},
        {"name": "Seated barbell shoulder press", "target": "Shoulders", "rating": 9.2, "data": []},
        {"name": "EZ-bar spider curl", "target": "Biceps", "rating": 9.2, "data": []},
        {"name": "Smith machine shrug", "target": "Traps", "rating": 9.2, "data": []},
        {"name": "Smith Machine Calf Raise", "target": "Calves", "rating": 9.2, "data": []},
        {"name": "Barbell walking lunge", "target": "Quadriceps", "rating": 9.2, "data": []},
        {"name": "Front Squats With Two Kettlebells", "target": "Quadriceps", "rating": 9.2, "data": []},
        {"name": "Reverse-grip bent-over row", "target": "Middle Back", "rating": 9.2, "data": []},
        {"name": "Seated Two-Arm Palms-Up Low-Pulley Wrist Curl", "target": "Forearms", "rating": 9.2, "data": []},
        {"name": "Close-grip bench press", "target": "Chest", "rating": 9.1, "data": []},
        {"name": "Dumbbell Flyes", "target": "Chest", "rating": 9.1, "data": []},
        {"name": "Hammer Curls", "target": "Biceps", "rating": 9.1, "data": []},
        {"name": "Incline dumbbell bench press", "target": "Chest", "rating": 9.1, "data": []},
        {"name": "Low-cable cross-over", "target": "Chest", "rating": 9.1, "data": []},
        {"name": "Single-arm high-cable side bend", "target": "Abdominals", "rating": 9.1, "data": []},
        {"name": "Seated Dumbbell Press", "target": "Shoulders", "rating": 9.1, "data": []},
        {"name": "Standing dumbbell shoulder press", "target": "Shoulders", "rating": 9.1, "data": []},
        {"name": "EZ-Bar Curl", "target": "Biceps", "rating": 9.1, "data": []},
        {"name": "Single-arm lateral raise", "target": "Shoulders", "rating": 9.1, "data": []},
        {"name": "Power Partials", "target": "Shoulders", "rating": 9.1, "data": []},
        {"name": "Leverage Shrug", "target": "Traps", "rating": 9.1, "data": []},
        {"name": "Cable V-bar push-down", "target": "Triceps", "rating": 9.1, "data": []},
        {"name": "Incline dumbbell reverse fly", "target": "Shoulders", "rating": 9.1, "data": []},
        {"name": "Kettlebell Pistol Squat", "target": "Quadriceps", "rating": 9.1, "data": []},
        {"name": "Overhead dumbbell front raise", "target": "Shoulders", "rating": 9.1, "data": []},
        {"name": "Biceps curl to shoulder press", "target": "Biceps", "rating": 9.1, "data": []},
        {"name": "Barbell Bench Press - Medium Grip", "target": "Chest", "rating": 9, "data": []},
        {"name": "Seated dumbbell shoulder press", "target": "Shoulders", "rating": 9, "data": []},
        {"name": "Barbell Curl", "target": "Biceps", "rating": 9, "data": []},
        {"name": "EZ-Bar Skullcrusher", "target": "Triceps", "rating": 9, "data": []},
        {"name": "One-Arm Dumbbell Row", "target": "Middle Back", "rating": 9, "data": []},
        {"name": "Alternating standing shoulder press", "target": "Shoulders", "rating": 9, "data": []},
        {"name": "Concentration curl", "target": "Biceps", "rating": 9, "data": []},
        {"name": "Decline Dumbbell Flyes", "target": "Chest", "rating": 9, "data": []},
        {"name": "Single-arm incline rear delt raise", "target": "Shoulders", "rating": 9, "data": []},
        {"name": "Alternating dumbbell front raise", "target": "Shoulders", "rating": 9, "data": []},
        {"name": "Narrow-stance squat", "target": "Quadriceps", "rating": 9, "data": []},
        {"name": "Kneeling cable oblique crunch", "target": "Abdominals", "rating": 9, "data": []},
        {"name": "Reverse Grip Triceps Pushdown", "target": "Triceps", "rating": 9, "data": []},
        {"name": "Snatch-Grip Behind-The-Neck Overhead Press", "target": "Shoulders", "rating": 9, "data": []},
        {"name": "Flexor Incline Dumbbell Curls", "target": "Biceps", "rating": 9, "data": []},
        {"name": "Seated One-Arm Dumbbell Palms-Up Wrist Curl", "target": "Forearms", "rating": 9, "data": []},
        {"name": "Thigh adductor", "target": "Adductors", "rating": 9, "data": []},
        {"name": "Machine Bicep Curl", "target": "Biceps", "rating": 9, "data": []},
        {"name": "Alternating Deltoid Raise", "target": "Shoulders", "rating": 9, "data": []},
        {"name": "Bodyweight Flyes", "target": "Chest", "rating": 9, "data": []},
        {"name": "Standing Calf Raises", "target": "Calves", "rating": 9, "data": []},
        {"name": "One-Arm Long Bar Row", "target": "Middle Back", "rating": 9, "data": []},
        {"name": "Overhead cable curl", "target": "Biceps", "rating": 9, "data": []},
        {"name": "Single-dumbbell front raise", "target": "Shoulders", "rating": 9, "data": []},
        {"name": "Incline cable chest fly", "target": "Chest", "rating": 9, "data": []},
        {"name": "Single-leg depth squat", "target": "Quadriceps", "rating": 9, "data": []},
        {"name": "Single-leg cable hip extension", "target": "Glutes", "rating": 9, "data": []},
        {"name": "Weighted Jump Squat", "target": "Quadriceps", "rating": 9, "data": []},
        {"name": "Kneeling cable triceps extension", "target": "Triceps", "rating": 9, "data": []},
        {"name": "Arnold press", "target": "Shoulders", "rating": 8.9, "data": []},
        {"name": "Single-arm cable triceps extension", "target": "Triceps", "rating": 8.9, "data": []},
        {"name": "Barbell roll-out", "target": "Abdominals", "rating": 8.9, "data": []},
        {"name": "Kneeling cable crunch", "target": "Abdominals", "rating": 8.9, "data": []},
        {"name": "Barbell Ab Rollout - On Knees", "target": "Abdominals", "rating": 8.9, "data": []},
        {"name": "Barbell Squat", "target": "Quadriceps", "rating": 8.9, "data": []},
        {"name": "Decline barbell bench press", "target": "Chest", "rating": 8.9, "data": []},
        {"name": "Dumbbell Bicep Curl", "target": "Biceps", "rating": 8.9, "data": []},
        {"name": "Dumbbell Goblet Squat", "target": "Quadriceps", "rating": 8.9, "data": []},
        {"name": "Dumbbell squat", "target": "Quadriceps", "rating": 8.9, "data": []},
        {"name": "Barbell front squat", "target": "Quadriceps", "rating": 8.9, "data": []},
        {"name": "Close-grip pull-down", "target": "Lats", "rating": 8.9, "data": []},
        {"name": "Smith machine shoulder press", "target": "Shoulders", "rating": 8.9, "data": []},
        {"name": "Seated triceps press", "target": "Triceps", "rating": 8.9, "data": []},
        {"name": "Wide-grip bench press", "target": "Chest", "rating": 8.9, "data": []},
        {"name": "Close-grip EZ-bar curl", "target": "Biceps", "rating": 8.9, "data": []},
        {"name": "Machine shoulder press", "target": "Shoulders", "rating": 8.9, "data": []},
        {"name": "Incline EZ-bar skullcrusher", "target": "Triceps", "rating": 8.9, "data": []},
        {"name": "Wide-Grip Decline Barbell Bench Press", "target": "Chest", "rating": 8.9, "data": []},
        {"name": "Decline Close-Grip Bench To Skull Crusher", "target": "Triceps", "rating": 8.9, "data": []},
        {"name": "Lying Leg Curls", "target": "Hamstrings", "rating": 8.9, "data": []},
        {"name": "Cross-body hammer curl", "target": "Biceps", "rating": 8.9, "data": []},
        {"name": "Shotgun row", "target": "Lats", "rating": 8.9, "data": []},
        {"name": "Reverse-grip incline dumbbell bench press", "target": "Chest", "rating": 8.9, "data": []},
        {"name": "Leg Press", "target": "Quadriceps", "rating": 8.8, "data": []},
        {"name": "Stiff-Legged Dumbbell Deadlift", "target": "Hamstrings", "rating": 8.8, "data": []},
        {"name": "Cable Crossover", "target": "Chest", "rating": 8.8, "data": []},
        {"name": "Barbell Incline Bench Press Medium-Grip", "target": "Chest", "rating": 8.8, "data": []},
        {"name": "Incline Dumbbell Flyes", "target": "Chest", "rating": 8.8, "data": []},
        {"name": "Seated Cable Rows", "target": "Middle Back", "rating": 8.8, "data": []},
        {"name": "Tricep Dumbbell Kickback", "target": "Triceps", "rating": 8.8, "data": []},
        {"name": "Barbell forward lunge", "target": "Quadriceps", "rating": 8.8, "data": []},
        {"name": "Close-Grip Front Lat Pulldown", "target": "Lats", "rating": 8.8, "data": []},
        {"name": "Dip Machine", "target": "Triceps", "rating": 8.8, "data": []},
        {"name": "Incline dumbbell row", "target": "Middle Back", "rating": 8.8, "data": []},
        {"name": "Dumbbell Lunges", "target": "Quadriceps", "rating": 8.8, "data": []},
        {"name": "Single-arm standing shoulder press", "target": "Shoulders", "rating": 8.8, "data": []},
        {"name": "Preacher Curl", "target": "Biceps", "rating": 8.8, "data": []},
        {"name": "Standing Dumbbell Triceps Extension", "target": "Triceps", "rating": 8.8, "data": []},
        {"name": "Bent Over Two-Dumbbell Row With Palms In", "target": "Middle Back", "rating": 8.8, "data": []},
        {"name": "Narrow-stance leg press", "target": "Quadriceps", "rating": 8.8, "data": []},
        {"name": "Barbell Curls Lying Against An Incline", "target": "Biceps", "rating": 8.8, "data": []},
        {"name": "Narrow Stance Hack Squats", "target": "Quadriceps", "rating": 8.8, "data": []},
        {"name": "Seated Close-Grip Concentration Barbell Curl", "target": "Biceps", "rating": 8.8, "data": []},
        {"name": "Smith machine box squat", "target": "Quadriceps", "rating": 8.8, "data": []},
        {"name": "Reverse Barbell Preacher Curls", "target": "Biceps", "rating": 8.8, "data": []},
        {"name": "Close-grip EZ-bar bench press", "target": "Chest", "rating": 8.8, "data": []},
        {"name": "Dumbbell front raise", "target": "Shoulders", "rating": 8.8, "data": []},
        {"name": "Neck Press", "target": "Chest", "rating": 8.8, "data": []},
        {"name": "Machine Squat", "target": "Quadriceps", "rating": 8.8, "data": []},
        {"name": "Standing One-Arm Cable Curl", "target": "Biceps", "rating": 8.8, "data": []},
        {"name": "Double-arm triceps kick-back", "target": "Triceps", "rating": 8.8, "data": []},
        {"name": "Dumbbell reverse lunge", "target": "Quadriceps", "rating": 8.7, "data": []},
        {"name": "Seated Calf Raise", "target": "Calves", "rating": 8.7, "data": []},
        {"name": "Standing dumbbell shrug", "target": "Traps", "rating": 8.7, "data": []},
        {"name": "Calf Press On The Leg Press Machine", "target": "Calves", "rating": 8.7, "data": []},
        {"name": "Barbell step-up", "target": "Quadriceps", "rating": 8.7, "data": []},
        {"name": "Bent Over Barbell Row", "target": "Middle Back", "rating": 8.7, "data": []},
        {"name": "Dumbbell Alternate Bicep Curl", "target": "Biceps", "rating": 8.7, "data": []},
        {"name": "Bent-over dumbbell rear delt row", "target": "Shoulders", "rating": 8.7, "data": []},
        {"name": "Single-arm dumbbell preacher curl", "target": "Biceps", "rating": 8.7, "data": []},
        {"name": "Smith machine back squat", "target": "Quadriceps", "rating": 8.7, "data": []},
        {"name": "Incline dumbbell front raise", "target": "Shoulders", "rating": 8.7, "data": []},
        {"name": "Alternate Incline Dumbbell Curl", "target": "Biceps", "rating": 8.7, "data": []},
        {"name": "Standing dumbbell upright row", "target": "Traps", "rating": 8.7, "data": []},
        {"name": "Single-arm cable front raise", "target": "Shoulders", "rating": 8.7, "data": []},
        {"name": "Two-Arm Kettlebell Military Press", "target": "Shoulders", "rating": 8.7, "data": []},
        {"name": "Incline cable chest press", "target": "Chest", "rating": 8.7, "data": []},
        {"name": "Standing Bradford press", "target": "Shoulders", "rating": 8.7, "data": []},
        {"name": "Neutral-grip dumbbell bench press", "target": "Chest", "rating": 8.7, "data": []},
        {"name": "Cable Chest Press", "target": "Chest", "rating": 8.7, "data": []},
        {"name": "Standing concentration curl", "target": "Biceps", "rating": 8.7, "data": []},
        {"name": "Kettlebell pass-through lunge", "target": "Hamstrings", "rating": 8.7, "data": []},
        {"name": "Straight-arm rope pull-down", "target": "Lats", "rating": 8.7, "data": []},
        {"name": "Barbell Shoulder Press", "target": "Shoulders", "rating": 8.7, "data": []},
        {"name": "Power clean", "target": "Hamstrings", "rating": 8.7, "data": []},
        {"name": "Kettlebell sumo deadlift high pull", "target": "Traps", "rating": 8.7, "data": []},
        {"name": "Calf-Machine Shoulder Shrug", "target": "Traps", "rating": 8.7, "data": []},
        {"name": "Rocking Standing Calf Raise", "target": "Calves", "rating": 8.7, "data": []},
        {"name": "Goblet Squat", "target": "Quadriceps", "rating": 8.7, "data": []},
        {"name": "Behind-the-head skullcrusher", "target": "Triceps", "rating": 8.7, "data": []},
        {"name": "Seated palms-up wrist curl", "target": "Forearms", "rating": 8.7, "data": []},
        {"name": "Reverse Cable Curl", "target": "Biceps", "rating": 8.7, "data": []},
        {"name": "Dumbbell side bend", "target": "Abdominals", "rating": 8.6, "data": []},
        {"name": "Lat pull-down", "target": "Lats", "rating": 8.6, "data": []},
        {"name": "Side Lateral Raise", "target": "Shoulders", "rating": 8.6, "data": []},
        {"name": "Alternating incline dumbbell biceps curl", "target": "Biceps", "rating": 8.6, "data": []},
        {"name": "Kettlebell One-Legged Deadlift", "target": "Hamstrings", "rating": 8.6, "data": []},
        {"name": "Alternate Hammer Curl", "target": "Biceps", "rating": 8.6, "data": []},
        {"name": "Triceps Pushdown", "target": "Triceps", "rating": 8.6, "data": []},
        {"name": "Low cable overhead triceps extension", "target": "Triceps", "rating": 8.6, "data": []},
        {"name": "Single-arm cable cross-over", "target": "Chest", "rating": 8.6, "data": []},
        {"name": "Seated dumbbell biceps curl", "target": "Biceps", "rating": 8.6, "data": []},
        {"name": "Rope Crunch", "target": "Abdominals", "rating": 8.6, "data": []},
        {"name": "Palms-Up Dumbbell Wrist Curl Over A Bench", "target": "Forearms", "rating": 8.6, "data": []},
        {"name": "Kettlebell thruster", "target": "Glutes", "rating": 8.6, "data": []},
        {"name": "Band Hip Adductions", "target": "Adductors", "rating": 8.6, "data": []},
        {"name": "Single-arm kettlebell clean", "target": "Hamstrings", "rating": 8.6, "data": []},
        {"name": "Preacher Hammer Dumbbell Curl", "target": "Biceps", "rating": 8.6, "data": []},
        {"name": "Alternating Kettlebell Press", "target": "Shoulders", "rating": 8.6, "data": []},
        {"name": "Split Squat with Dumbbells", "target": "Quadriceps", "rating": 8.6, "data": []},
        {"name": "Single-arm kettlebell snatch", "target": "Shoulders", "rating": 8.6, "data": []},
        {"name": "Close-grip barbell curl", "target": "Biceps", "rating": 8.6, "data": []},
        {"name": "Standing cable crunch", "target": "Abdominals", "rating": 8.6, "data": []},
        {"name": "Leverage Incline Chest Press", "target": "Chest", "rating": 8.6, "data": []},
        {"name": "Standing barbell overhead triceps extension", "target": "Triceps", "rating": 8.6, "data": []},
        {"name": "Lying cable triceps extension", "target": "Triceps", "rating": 8.6, "data": []},
        {"name": "Cable Internal Rotation", "target": "Shoulders", "rating": 8.6, "data": []},
        {"name": "Leg Extensions", "target": "Quadriceps", "rating": 8.5, "data": []},
        {"name": "Single-arm dumbbell triceps extension", "target": "Triceps", "rating": 8.5, "data": []},
        {"name": "Butterfly", "target": "Chest", "rating": 8.5, "data": []},
        {"name": "Decline dumbbell bench press", "target": "Chest", "rating": 8.5, "data": []},
        {"name": "Seated face pull", "target": "Shoulders", "rating": 8.5, "data": []},
        {"name": "Barbell Bulgarian split squat", "target": "Quadriceps", "rating": 8.5, "data": []},
        {"name": "Reverse-grip lat pull-down", "target": "Lats", "rating": 8.5, "data": []},
        {"name": "Standing Biceps Cable Curl", "target": "Biceps", "rating": 8.5, "data": []},
        {"name": "Single-arm cable seated row", "target": "Middle Back", "rating": 8.5, "data": []},
        {"name": "Single-arm kettlebell row", "target": "Chest", "rating": 8.5, "data": []},
        {"name": "Drag curl", "target": "Biceps", "rating": 8.5, "data": []},
        {"name": "Dumbbell external shoulder rotation", "target": "Shoulders", "rating": 8.5, "data": []},
        {"name": "Single-arm bent-over cable rear delt fly", "target": "Shoulders", "rating": 8.5, "data": []},
        {"name": "Single-arm incline lateral raise", "target": "Shoulders", "rating": 8.5, "data": []},
        {"name": "Decline bar press sit-up", "target": "Abdominals", "rating": 8.5, "data": []},
        {"name": "Barbell rear delt bent-over row", "target": "Shoulders", "rating": 8.5, "data": []},
        {"name": "Calf Press", "target": "Calves", "rating": 8.5, "data": []},
        {"name": "Kettlebell alternating renegade row", "target": "Middle Back", "rating": 8.5, "data": []},
        {"name": "Bosu Ball Cable Crunch With Side Bends", "target": "Abdominals", "rating": 8.5, "data": []},
        {"name": "Hammer Grip Incline DB Bench Press", "target": "Chest", "rating": 8.5, "data": []},
        {"name": "Decline Dumbbell Triceps Extension", "target": "Triceps", "rating": 8.5, "data": []},
        {"name": "Seated cable shoulder press", "target": "Shoulders", "rating": 8.5, "data": []},
        {"name": "Barbell hack squat", "target": "Quadriceps", "rating": 8.5, "data": []},
        {"name": "Leverage Chest Press", "target": "Chest", "rating": 8.5, "data": []},
        {"name": "Seated rear delt fly", "target": "Shoulders", "rating": 8.4, "data": []},
        {"name": "Standing face pull", "target": "Shoulders", "rating": 8.4, "data": []},
        {"name": "Barbell shrug", "target": "Traps", "rating": 8.4, "data": []},
        {"name": "Standing cable rear delt row", "target": "Shoulders", "rating": 8.4, "data": []},
        {"name": "Hack Squat", "target": "Quadriceps", "rating": 8.4, "data": []},
        {"name": "Dumbbell skullcrusher", "target": "Triceps", "rating": 8.4, "data": []},
        {"name": "Man-maker", "target": "Middle Back", "rating": 8.4, "data": []},
        {"name": "Straight-arm dumbbell pull-over", "target": "Chest", "rating": 8.4, "data": []},
        {"name": "Decline Smith Press", "target": "Chest", "rating": 8.4, "data": []},
        {"name": "Cable cross-over", "target": "Chest", "rating": 8.4, "data": []},
        {"name": "One Arm Pronated Dumbbell Triceps Extension", "target": "Triceps", "rating": 8.4, "data": []},
        {"name": "Single-arm kettlebell clean and jerk", "target": "Shoulders", "rating": 8.4, "data": []},
        {"name": "Incline Dumbbell Bench With Palms Facing In", "target": "Chest", "rating": 8.4, "data": []},
        {"name": "Seated palms-down wrist curl", "target": "Forearms", "rating": 8.4, "data": []},
        {"name": "Machine seated row", "target": "Lats", "rating": 8.4, "data": []},
        {"name": "Dumbbell Raise", "target": "Shoulders", "rating": 8.4, "data": []},
        {"name": "Palms-Down Dumbbell Wrist Curl Over A Bench", "target": "Forearms", "rating": 8.4, "data": []},
        {"name": "One Arm Supinated Dumbbell Triceps Extension", "target": "Triceps", "rating": 8.4, "data": []},
        {"name": "Dumbbell bent-over row", "target": "Middle Back", "rating": 8.3, "data": []},
        {"name": "Barbell thruster", "target": "Quadriceps", "rating": 8.3, "data": []},
        {"name": "Dumbbell sumo squat", "target": "Quadriceps", "rating": 8.3, "data": []},
        {"name": "Barbell upright row", "target": "Shoulders", "rating": 8.3, "data": []},
        {"name": "Straight-Arm Pulldown", "target": "Lats", "rating": 8.3, "data": []},
        {"name": "Barbell stiff-legged deadlift", "target": "Hamstrings", "rating": 8.3, "data": []},
        {"name": "Smith machine bench press", "target": "Chest", "rating": 8.3, "data": []},
        {"name": "Seated Side Lateral Raise", "target": "Shoulders", "rating": 8.3, "data": []},
        {"name": "Dumbbell Lying Rear Lateral Raise", "target": "Shoulders", "rating": 8.3, "data": []},
        {"name": "Dumbbell preacher curl", "target": "Biceps", "rating": 8.3, "data": []},
        {"name": "Front Raise And Pullover", "target": "Chest", "rating": 8.3, "data": []},
        {"name": "Middle Back Shrug", "target": "Middle Back", "rating": 8.3, "data": []},
        {"name": "Incline face-down bar front raise", "target": "Shoulders", "rating": 8.3, "data": []},
        {"name": "Seated One-Arm Dumbbell Palms-Down Wrist Curl", "target": "Forearms", "rating": 8.3, "data": []},
        {"name": "Yates Row Reverse Grip", "target": "Middle Back", "rating": 8.3, "data": []},
        {"name": "Reverse-grip bench press", "target": "Triceps", "rating": 8.3, "data": []},
        {"name": "Leverage Decline Chest Press", "target": "Chest", "rating": 8.3, "data": []},
        {"name": "Bench barbell roll-out", "target": "Abdominals", "rating": 8.3, "data": []},
        {"name": "Barbell behind-the-back shrug", "target": "Traps", "rating": 8.3, "data": []},
        {"name": "Lying Supine Dumbbell Curl", "target": "Biceps", "rating": 8.3, "data": []},
        {"name": "Internal Rotation with Band", "target": "Shoulders", "rating": 8.3, "data": []},
        {"name": "Machine Preacher Curls", "target": "Biceps", "rating": 8.3, "data": []},
        {"name": "Bottoms-Up Clean From The Hang Position", "target": "Forearms", "rating": 8.3, "data": []},
        {"name": "Single-arm kneeling lat pull-down", "target": "Lats", "rating": 8.3, "data": []},
        {"name": "Elevated Cable Rows", "target": "Lats", "rating": 8.3, "data": []},
        {"name": "Incline Dumbbell Flyes - With A Twist", "target": "Chest", "rating": 8.3, "data": []},
        {"name": "Cross Over - With Bands", "target": "Chest", "rating": 8.3, "data": []},
        {"name": "Standing Low-Pulley Deltoid Raise", "target": "Shoulders", "rating": 8.3, "data": []},
        {"name": "Advanced Kettlebell Windmill", "target": "Abdominals", "rating": 8.3, "data": []},
        {"name": "Dumbbell step-up", "target": "Quadriceps", "rating": 8.2, "data": []},
        {"name": "Bent-arm dumbbell pull-over", "target": "Chest", "rating": 8.2, "data": []},
        {"name": "Reverse-grip barbell curl", "target": "Biceps", "rating": 8.2, "data": []},
        {"name": "Standing Cable Wood Chop", "target": "Abdominals", "rating": 8.2, "data": []},
        {"name": "Band Pull Apart", "target": "Shoulders", "rating": 8.2, "data": []},
        {"name": "Cable rope hammer curl", "target": "Biceps", "rating": 8.2, "data": []},
        {"name": "Standing crossed-cable rear delt fly", "target": "Shoulders", "rating": 8.2, "data": []},
        {"name": "Reverse Machine Flyes", "target": "Shoulders", "rating": 8.2, "data": []},
        {"name": "Single-leg kettlebell deadlift", "target": "Hamstrings", "rating": 8.2, "data": []},
        {"name": "Machine chest press", "target": "Chest", "rating": 8.2, "data": []},
        {"name": "Bradford/Rocky Presses", "target": "Shoulders", "rating": 8.2, "data": []},
        {"name": "Incline anti-gravity shoulder press", "target": "Shoulders", "rating": 8.2, "data": []},
        {"name": "Barbell back squat", "target": "Quadriceps", "rating": 8.2, "data": []},
        {"name": "Cable reverse crunch", "target": "Abdominals", "rating": 8.2, "data": []},
        {"name": "Cable Hip Adduction", "target": "Quadriceps", "rating": 8.2, "data": []},
        {"name": "Machine-assisted pull-up", "target": "Lats", "rating": 8.2, "data": []},
        {"name": "Standing Cable Chest Press", "target": "Chest", "rating": 8.2, "data": []},
        {"name": "Lying cable biceps curl", "target": "Biceps", "rating": 8.2, "data": []},
        {"name": "Seated Back Extension", "target": "Lower Back", "rating": 8.2, "data": []},
        {"name": "Low Cable Triceps Extension", "target": "Triceps", "rating": 8.2, "data": []},
        {"name": "Head-on-bench dumbbell rear delt raise", "target": "Shoulders", "rating": 8.2, "data": []},
        {"name": "Pendlay Row", "target": "Middle Back", "rating": 8.2, "data": []},
        {"name": "Lying rear delt fly", "target": "Shoulders", "rating": 8.2, "data": []},
        {"name": "Seated Bent-Over Two-Arm Dumbbell Triceps Extension", "target": "Triceps", "rating": 8.2, "data": []},
        {"name": "Thigh abductor", "target": "Abductors", "rating": 8.2, "data": []},
        {"name": "Standing barbell calf raise", "target": "Calves", "rating": 8.2, "data": []},
        {"name": "Romanian Deadlift", "target": "Hamstrings", "rating": 8.1, "data": []},
        {"name": "Cable overhead triceps extension", "target": "Triceps", "rating": 8.1, "data": []},
        {"name": "Smith machine bent-over row", "target": "Middle Back", "rating": 8.1, "data": []},
        {"name": "Cable straight-bar upright row", "target": "Traps", "rating": 8.1, "data": []},
        {"name": "Close-grip dumbbell bench press", "target": "Chest", "rating": 8.1, "data": []},
        {"name": "Zercher squat", "target": "Quadriceps", "rating": 8.1, "data": []},
        {"name": "Full Range-Of-Motion Lat Pulldown", "target": "Lats", "rating": 8.1, "data": []},
        {"name": "Cable Shoulder Press", "target": "Shoulders", "rating": 8.1, "data": []},
        {"name": "Cable Russian Twists", "target": "Abdominals", "rating": 8.1, "data": []},
        {"name": "EZ-bar skullcrusher-", "target": "Triceps", "rating": 8.1, "data": []},
        {"name": "Stiff Leg Barbell Good Morning", "target": "Lower Back", "rating": 8.1, "data": []},
        {"name": "Standing Dumbbell Reverse Curl", "target": "Biceps", "rating": 8.1, "data": []},
        {"name": "Lying Close-Grip Barbell Triceps Press To Chin", "target": "Triceps", "rating": 8.1, "data": []},
        {"name": "Tate Press", "target": "Triceps", "rating": 8.1, "data": []},
        {"name": "Back Flyes - With Bands", "target": "Shoulders", "rating": 8.1, "data": []},
        {"name": "Ab Crunch Machine", "target": "Abdominals", "rating": 8, "data": []},
        {"name": "Smith Machine Incline Bench Press", "target": "Chest", "rating": 8, "data": []},
        {"name": "Machine Shoulder (Military) Press", "target": "Shoulders", "rating": 8, "data": []},
        {"name": "Cuban press", "target": "Shoulders", "rating": 8, "data": []},
        {"name": "Reverse Flyes With External Rotation", "target": "Shoulders", "rating": 8, "data": []},
        {"name": "Bent-arm barbell pull-over", "target": "Lats", "rating": 8, "data": []},
        {"name": "Smith Machine Close-Grip Bench Press", "target": "Chest", "rating": 8, "data": []},
        {"name": "Palms-out incline biceps curl", "target": "Biceps", "rating": 8, "data": []},
        {"name": "Alternating Cable Shoulder Press", "target": "Shoulders", "rating": 8, "data": []},
        {"name": "Romanian Deadlift with Kettlebell", "target": "Hamstrings", "rating": 8, "data": []},
        {"name": "Smith machine leg press", "target": "Quadriceps", "rating": 8, "data": []},
        {"name": "Jefferson Squats", "target": "Quadriceps", "rating": 8, "data": []},
        {"name": "Single-arm low cable triceps extension", "target": "Triceps", "rating": 8, "data": []},
        {"name": "Smith machine straight-legged hip raise", "target": "Abdominals", "rating": 8, "data": []},
        {"name": "Reverse Hyperextension", "target": "Hamstrings", "rating": 8, "data": []},
        {"name": "Kettlebell plyo push-up", "target": "Chest", "rating": 8, "data": []},
        {"name": "Lying Machine Squat", "target": "Quadriceps", "rating": 8, "data": []},
        {"name": "Seated Leg Curl", "target": "Hamstrings", "rating": 7.9, "data": []},
        {"name": "Standing Barbell Press Behind Neck", "target": "Shoulders", "rating": 7.9, "data": []},
        {"name": "Close-Grip EZ-Bar Curl with Band", "target": "Biceps", "rating": 7.9, "data": []},
        {"name": "Alternating Kettlebell Row", "target": "Middle Back", "rating": 7.9, "data": []},
        {"name": "Single-arm side lying rear fly", "target": "Shoulders", "rating": 7.9, "data": []},
        {"name": "Cable shrug", "target": "Traps", "rating": 7.9, "data": []},
        {"name": "Pallof press with rotation", "target": "Abdominals", "rating": 7.9, "data": []},
        {"name": "Kneeling lat pull-down", "target": "Lats", "rating": 7.9, "data": []},
        {"name": "Standing Bent-Over One-Arm Dumbbell Triceps Extension", "target": "Triceps", "rating": 7.9, "data": []},
        {"name": "Lateral Raise - With Bands", "target": "Shoulders", "rating": 7.9, "data": []},
        {"name": "Leverage High Row", "target": "Middle Back", "rating": 7.9, "data": []},
        {"name": "Single-arm dumbbell upright row", "target": "Shoulders", "rating": 7.8, "data": []},
        {"name": "Smith machine behind-the-back shrug", "target": "Traps", "rating": 7.8, "data": []},
        {"name": "Kettlebell pirate ship", "target": "Shoulders", "rating": 7.8, "data": []},
        {"name": "Dumbbell Scaption", "target": "Shoulders", "rating": 7.8, "data": []},
        {"name": "Cable Wrist Curl", "target": "Forearms", "rating": 7.8, "data": []},
        {"name": "Upright Row - With Bands", "target": "Traps", "rating": 7.8, "data": []},
        {"name": "Barbell side split squat", "target": "Quadriceps", "rating": 7.8, "data": []},
        {"name": "See-Saw Press (Alternating Side Press)", "target": "Shoulders", "rating": 7.8, "data": []},
        {"name": "Kettlebell Windmill", "target": "Abdominals", "rating": 7.7, "data": []},
        {"name": "Seated Leg Press", "target": "Quadriceps", "rating": 7.7, "data": []},
        {"name": "Straight-arm plank with biceps curl", "target": "Biceps", "rating": 7.7, "data": []},
        {"name": "Cable Deadlifts", "target": "Quadriceps", "rating": 7.7, "data": []},
        {"name": "Cable Seated Crunch", "target": "Abdominals", "rating": 7.7, "data": []},
        {"name": "Kettlebell Curtsy Lunge", "target": "Quadriceps", "rating": 7.7, "data": []},
        {"name": "Smith machine Bulgarian split squat", "target": "Quadriceps", "rating": 7.7, "data": []},
        {"name": "Barbell speed squat", "target": "Quadriceps", "rating": 7.7, "data": []},
        {"name": "Face-down incline dumbbell biceps curl", "target": "Biceps", "rating": 7.6, "data": []},
        {"name": "Shoulder Press - With Bands", "target": "Shoulders", "rating": 7.6, "data": []},
        {"name": "Band-assisted pull-up", "target": "Lats", "rating": 7.6, "data": []},
        {"name": "Barbell Bench Press-Wide Grip", "target": "Chest", "rating": 7.6, "data": []},
        {"name": "Barbell Seated Calf Raise", "target": "Calves", "rating": 7.6, "data": []},
        {"name": "Single-arm side deadlift", "target": "Quadriceps", "rating": 7.5, "data": []},
        {"name": "Two-Arm Kettlebell Clean", "target": "Shoulders", "rating": 7.5, "data": []},
        {"name": "Cable rope preacher hammer curl", "target": "Biceps", "rating": 7.5, "data": []},
        {"name": "Seated Bent-Over One-Arm Dumbbell Triceps Extension", "target": "Triceps", "rating": 7.5, "data": []},
        {"name": "Double Kettlebell Push Press", "target": "Shoulders", "rating": 7.5, "data": []},
        {"name": "Barbell front raise", "target": "Shoulders", "rating": 7.4, "data": []},
        {"name": "Machine Triceps Extension", "target": "Triceps", "rating": 7.4, "data": []},
        {"name": "Seated Dumbbell Inner Biceps Curl", "target": "Biceps", "rating": 7.4, "data": []},
        {"name": "Barbell Squat To A Bench", "target": "Quadriceps", "rating": 7.4, "data": []},
        {"name": "Dumbbell Incline Shoulder Raise", "target": "Shoulders", "rating": 7.4, "data": []},
        {"name": "Standing Inner-Biceps Curl", "target": "Biceps", "rating": 7.4, "data": []},
        {"name": "Single-arm kettlebell swing", "target": "Hamstrings", "rating": 7.4, "data": []},
        {"name": "Pull Through", "target": "Glutes", "rating": 7.4, "data": []},
        {"name": "Standing Leg Curl", "target": "Hamstrings", "rating": 7.4, "data": []},
        {"name": "Lying cable chest fly", "target": "Chest", "rating": 7.3, "data": []},
        {"name": "Single-arm pull-down", "target": "Lats", "rating": 7.3, "data": []},
        {"name": "Dumbbell Walking Lunge", "target": "Quadriceps", "rating": 7.3, "data": []},
        {"name": "Two-Arm Kettlebell Row", "target": "Middle Back", "rating": 7.3, "data": []},
        {"name": "One Arm Floor Press", "target": "Triceps", "rating": 7.3, "data": []},
        {"name": "Kettlebell Pass Between The Legs", "target": "Abdominals", "rating": 7.3, "data": []},
        {"name": "Wide-Grip Decline Barbell Pullover", "target": "Chest", "rating": 7.3, "data": []},
        {"name": "Smith machine upright row", "target": "Traps", "rating": 7.3, "data": []},
        {"name": "Smith Machine Decline Press", "target": "Chest", "rating": 7.3, "data": []},
        {"name": "Smith Machine Reverse Calf Raises", "target": "Calves", "rating": 7.3, "data": []},
        {"name": "Single-dumbbell push-up", "target": "Chest", "rating": 7.3, "data": []},
        {"name": "Overhead bar front raise", "target": "Shoulders", "rating": 7.2, "data": []},
        {"name": "Single-arm Smith machine upright row", "target": "Shoulders", "rating": 7.2, "data": []},
        {"name": "Hip Extension with Bands", "target": "Glutes", "rating": 7.2, "data": []},
        {"name": "Machine Lateral Raise", "target": "Shoulders", "rating": 7.2, "data": []},
        {"name": "Lying Close-Grip Bar Curl On High Pulley", "target": "Biceps", "rating": 7.1, "data": []},
        {"name": "Behind-the-neck pull-down", "target": "Lats", "rating": 7.1, "data": []},
        {"name": "Incline cable straight-bar triceps extension", "target": "Triceps", "rating": 7.1, "data": []},
        {"name": "Smith machine pistol squat", "target": "Quadriceps", "rating": 7, "data": []},
        {"name": "Dumbbell Squat To A Bench", "target": "Quadriceps", "rating": 7, "data": []},
        {"name": "Kettlebell Seated Press", "target": "Shoulders", "rating": 7, "data": []},
        {"name": "Smith machine stiff-legged deadlift", "target": "Hamstrings", "rating": 7, "data": []},
        {"name": "Single-arm kettlebell overhead squat", "target": "Quadriceps", "rating": 7, "data": []},
        {"name": "Barbell Side Bend", "target": "Abdominals", "rating": 7, "data": []},
        {"name": "Double Kettlebell Jerk", "target": "Shoulders", "rating": 7, "data": []},
        {"name": "Kettlebell Arnold Press", "target": "Shoulders", "rating": 6.8, "data": []},
        {"name": "Barbell Guillotine Bench Press", "target": "Chest", "rating": 6.7, "data": []},
        {"name": "Cable Seated Lateral Raise", "target": "Shoulders", "rating": 6.5, "data": []},
        {"name": "One-Arm Flat Bench Dumbbell Flye", "target": "Chest", "rating": 6.5, "data": []},
        {"name": "Incline barbell shoulder protraction", "target": "Shoulders", "rating": 6.5, "data": []},
        {"name": "Straight Bar Bench Mid Rows", "target": "Middle Back", "rating": 6.5, "data": []},
        {"name": "Extended Range One-Arm Kettlebell Floor Press", "target": "Chest", "rating": 6.3, "data": []},
        {"name": "Dumbbell Tricep Extension -Pronated Grip", "target": "Triceps", "rating": 6.3, "data": []},
        {"name": "Seated Dumbbell Palms-Up Wrist Curl", "target": "Forearms", "rating": 6.2, "data": []},
        {"name": "Barbell seal row", "target": "Middle Back", "rating": 6.2, "data": []},
        {"name": "Kettlebell alternating floor press", "target": "Chest", "rating": 6, "data": []},
        {"name": "Lying High Bench Barbell Curl", "target": "Biceps", "rating": 5.8, "data": []},
        {"name": "Squats - With Bands", "target": "Quadriceps", "rating": 5.8, "data": []},
        {"name": "Bench Press - With Bands", "target": "Chest", "rating": 5.5, "data": []},
        {"name": "Front Barbell Squat To A Bench", "target": "Quadriceps", "rating": 5.3, "data": []},
        {"name": "Kettlebell Dead Clean", "target": "Hamstrings", "rating": 5.3, "data": []},
        {"name": "Partner farmer's walk", "target": "Forearms", "rating": 5.3, "data": []},
        {"name": "Cable Judo Flip", "target": "Abdominals", "rating": 5, "data": []},
        {"name": "Alternating Hang Clean", "target": "Hamstrings", "rating": 4.9, "data": []},
        {"name": "Calf Raises - With Bands", "target": "Calves", "rating": 4.8, "data": []},
        {"name": "Calf Raise On A Dumbbell", "target": "Calves", "rating": 4.8, "data": []},
        {"name": "Seated bar twist", "target": "Abdominals", "rating": 4.7, "data": []},
        {"name": "Double-kettlebell windmill", "target": "Shoulders", "rating": 3, "data": []},
        {"name": "Single-arm half-kneeling shoulder press", "target": "Shoulders", "rating": 0, "data": []},
        {"name": "Dumbbell thruster", "target": "Quadriceps", "rating": 0, "data": []},
        {"name": "Partner Facing Feet-Elevated Side Plank With Band Row", "target": "Middle Back", "rating": 0, "data": []},
        {"name": "Barbell reverse lunge", "target": "Quadriceps", "rating": 0, "data": []},
        {"name": "One-Arm Kettlebell Floor Press", "target": "Chest", "rating": 0, "data": []},
        {"name": "JM Press With Bands", "target": "Triceps", "rating": 0, "data": []},
        {"name": "Kettlebell side squat", "target": "Quadriceps", "rating": 0, "data": []},
        {"name": "Barbell pull-over to press", "target": "Lats", "rating": 0, "data": []},
        {"name": "Dumbbell suitcase carry", "target": "Forearms", "rating": 0, "data": []},
        {"name": "Dumbbell front squat", "target": "Quadriceps", "rating": 0, "data": []},
        {"name": "Close-stance dumbbell front squat", "target": "Quadriceps", "rating": 0, "data": []},
        {"name": "One-Arm Kettlebell Split Snatch", "target": "Shoulders", "rating": 0, "data": []},
        {"name": "Front Squat (Clean Grip)", "target": "Quadriceps", "rating": 0, "data": []},
        {"name": "Hip Flexion with Band", "target": "Quadriceps", "rating": 0, "data": []},
        {"name": "Leg-Over Floor Press", "target": "Chest", "rating": 0, "data": []},
        {"name": "Barbell front squat to back squat", "target": "Quadriceps", "rating": 0, "data": []},
        {"name": "One-Arm Kettlebell Para Press", "target": "Shoulders", "rating": 0, "data": []},
        {"name": "Squat Jerk", "target": "Quadriceps", "rating": 0, "data": []},
        {"name": "One-Arm Open Palm Kettlebell Clean", "target": "Hamstrings", "rating": 0, "data": []},
        {"name": "Barbell Front-To-Back Squat", "target": "Quadriceps", "rating": 0, "data": []},
        {"name": "Single-Arm Dumbbell Overhead Squat", "target": "Quadriceps", "rating": 0, "data": []},
        {"name": "External Rotation with Band", "target": "Shoulders", "rating": 0, "data": []},
        {"name": "Forward Band Walk", "target": "Quadriceps", "rating": 0, "data": []},
        {"name": "Stiff-Legged Deadlift", "target": "Hamstrings", "rating": 0, "data": []},
        {"name": "Open Palm Kettlebell Clean", "target": "Hamstrings", "rating": 0, "data": []},
        {"name": "Box Squat with Chains", "target": "Quadriceps", "rating": 0, "data": []},
        {"name": "Smith Incline Shoulder Raise", "target": "Shoulders", "rating": 0, "data": []},
        {"name": "V-sit with overhead triceps extension", "target": "Triceps", "rating": 0, "data": []},
        {"name": "JM Press", "target": "Triceps", "rating": 0, "data": []},
        {"name": "One-Arm Kettlebell Split Jerk", "target": "Shoulders", "rating": 0, "data": []},
        {"name": "Yates Row", "target": "Middle Back", "rating": 0, "data": []},
        {"name": "Kettlebell sumo squat", "target": "Quadriceps", "rating": 0, "data": []},
        {"name": "One-Arm Kettlebell Military Press To The Side", "target": "Shoulders", "rating": 0, "data": []},
        {"name": "One-Arm Kettlebell Jerk", "target": "Shoulders", "rating": 0, "data": []},
        {"name": "Snatch Pull", "target": "Hamstrings", "rating": 0, "data": []},
        {"name": "Double Kettlebell Snatch", "target": "Shoulders", "rating": 0, "data": []},
        {"name": "Dumbbell lunge with biceps curl", "target": "Quadriceps", "rating": 0, "data": []},
        {"name": "Kettlebell 3-point leg extension", "target": "Abdominals", "rating": 0, "data": []},
        {"name": "Dumbbell Pistol Squat", "target": "Quadriceps", "rating": 0, "data": []},
        {"name": "Front Squat (Bodybuilder)", "target": "Quadriceps", "rating": 0, "data": []},
        {"name": "Kettlebell Hang Clean", "target": "Hamstrings", "rating": 0, "data": []},
        {"name": "Dumbbell Squat Snatch", "target": "Quadriceps", "rating": 0, "data": []},
        {"name": "Barbell step-down reverse lunge", "target": "Quadriceps", "rating": 0, "data": []},
        {"name": "Double Kettlebell Alternating Hang Clean", "target": "Hamstrings", "rating": 0, "data": []},
        {"name": "Dumbbell Clean And Jerk", "target": "Shoulders", "rating": 0, "data": []},
        {"name": "Kettlebell thruster progression", "target": "Quadriceps", "rating": 0, "data": []},
        {"name": "Partner side plank band row", "target": "Middle Back", "rating": 0, "data": []},
        {"name": "Plate Row", "target": "Middle Back", "rating": 0, "data": []},
        {"name": "Kettlebell power clean", "target": "Quadriceps", "rating": 0, "data": []},
        {"name": "Seated wide-grip curl to close-grip curl", "target": "Biceps", "rating": 0, "data": []},
        {"name": "Assisted Chin-Up", "target": "Lats", "rating": 0, "data": []},
        {"name": "Band overhead triceps press", "target": "Triceps", "rating": 0, "data": []},
        {"name": "Dumbbell Alternating Lunge", "target": "Quadriceps", "rating": 0, "data": []},
        {"name": "Suitcase Dumbbell Carry", "target": "Forearms", "rating": 0, "data": []},
        {"name": "Smith machine bench press throw", "target": "Chest", "rating": 0, "data": []},
        {"name": "Seated Straigh-Bar Curl Superset", "target": "Biceps", "rating": 0, "data": []},
        {"name": "Lateral Band Walk", "target": "Abductors", "rating": 0, "data": []},
        {"name": "Leverage Deadlift", "target": "Quadriceps", "rating": 0, "data": []},
        {"name": "Feet-Elevated TRX Push-Up", "target": "Chest", "rating": 0, "data": []},
        {"name": "Barbell Deadlift Bent Row Complex", "target": "Middle Back", "rating": 0, "data": []},
        {"name": "Dumbbell Side Lunge", "target": "Quadriceps", "rating": 0, "data": []},
        {"name": "Two-Arm Kettlebell Jerk", "target": "Shoulders", "rating": 0, "data": []},
        {"name": "Single-Arm Landmine Row", "target": "Middle Back", "rating": 0, "data": []},
        {"name": "Partner plank band row", "target": "Abdominals", "rating": 0, "data": []},
        {"name": "Single Arm Overhead Kettlebell Squat", "target": "Quadriceps", "rating": 0, "data": []},
    ],
    "programs": {
        "PPL": {
            "info": [
                { "day": "Push", "workouts": [{ "name": "Barbell Bench Press", "rep_range": "3-6", "sets": 4 },{ "name": "Dumbbell Bench Press", "rep_range": "3-6", "sets": 4 }, { "name": "Dips", "rep_range": "8-12", "sets": 4 }, { "name": "Flys", "rep_range": "8-12", "sets": 2 }] },
                { "day": "Pull", "workouts": [{ "name": "Barbell Bicep Curls", "rep_range": "8-12", "sets": 4 }, { "name": "Dumbell Bicep Curls", "rep_range": "8-12", "sets": 4 }, { "name": "Hammer Curls", "rep_range": "8-12", "sets": 4 }] },
                { "day": "Legs", "workouts": [{ "name": "Barbell Squats", "rep_range": "3-6", "sets": 4 }] },
                { "day": "Rest", "workouts": [] }],
            "state": {
                "currentDayIndex": 0,
                "exercises": []
            }
        },
        "Arnold": {
            "info": [
                { "day": "Arms, Shoulders, Abs", "workouts": [{ "name": "Barbell Bicep Curls", "rep_range": "8-12", "sets": 2 }, { "name": "Dumbell Bicep Curls", "rep_range": "8-12", "sets": 2 }] },
                { "day": "Rest", "workouts": [] },
                { "day": "Arms, Shoulders, Abs", "workouts": [{ "name": "Barbell Bicep Curls", "rep_range": "8-12", "sets": 2 }, { "name": "Hammer Curls", "rep_range": "8-12", "sets": 2 }] },
                { "day": "Rest", "workouts": [] }],
            "state": {
                "currentDayIndex": 0,
                "exercises": []
            }
        },
        "Test": {
            "info": [
                { "day": "Push", "workouts": [{ "name": "Barbell Bench Press", "rep_range": "3-6", "sets": 2 }] },
                { "day": "Pull", "workouts": [{ "name": "Barbell Bicep Curls", "rep_range": "8-12", "sets": 2 }] },
                { "day": "Legs", "workouts": [{ "name": "Barbell Squats", "rep_range": "3-6", "sets": 2 }] },
                { "day": "Rest", "workouts": [] }],
            "state": {
                "currentDayIndex": 0,
                "exercises": []
            }
        }
    },
    "state": {
        "selectedProgram": null,
    }
}

const FileSystemCommands = {
    async setupProject() {
        if ((await FileSystem.getInfoAsync(dir + "workouts.json")).exists) {
            // this.createWorkoutFiles() //uncomment to reset user data to starterJSON
            return this.getWorkouts()
        } else {
            this.createWorkoutFiles()
            return this.getWorkouts()
        }
    },
    async createWorkoutFiles() {
        // console.log("in createWorkoutFiles")
        // console.log("workouts",workouts.workouts.Arms['Barbell Bicep Curls'])
        try {
            await FileSystem.writeAsStringAsync(dir + "workouts.json", JSON.stringify(starterJSON));
        } catch (error) {
            console.error(error);
        }
    },
    async updateWorkoutFiles(data) {
        // console.log("in updateWorkoutFiles")
        // data.workouts.forEach(program => console.log(program.name, program.targets, program.data))
        try {
            await FileSystem.writeAsStringAsync(dir + "workouts.json", JSON.stringify(data));
        } catch (error) {
            console.error(error);
        }
    },
    async getWorkouts() {
        // console.log("in getWorkouts")
        try {
            var workouts = await FileSystem.readAsStringAsync(dir + "workouts.json")
            workouts = JSON.parse(workouts)
            // console.log("workouts", workouts)
            // workouts = Object.entries(workouts);

            return workouts
        } catch (error) {
            console.error(error);
        }
    },
    async deleteFiles() {
        // console.log("in deleteFiles", await FileSystem.readDirectoryAsync(dir), dir)
        try {
            await FileSystem.deleteAsync(dir + "workouts.json")
            // console.log("after deleteFiles", await FileSystem.readDirectoryAsync(dir))
            return true
        } catch (error) {
            console.error(error);
        }
        return false
    }
}

export default FileSystemCommands
